name: Rpg
version: '1.0'
main: Perdume.rpg.Rpg
api-version: '1.21.4'
author: Perdume

depend: [Vault, AuraSkills] # 이 줄을 추가합니다.

commands:
  # [수정] 보상
  보상:
    description: 보상 수령함을 엽니다.
    aliases: [reward]

  # [수정] 파티
  파티:
    description: 파티를 관리합니다.
    aliases: [party, p]

  # [수정] 레이드
  레이드:
    description: 레이드를 시작합니다.
    aliases: [raid]
    permission: rpg.raid.start

  섬:
    description: 섬 관련 명령어
    aliases: [island, is]
  스폰:
    description: 스폰 명령어
    aliases: [spawn, 넴주, lobby, 로비, l]
  스포너분석:
    description: 스포너
    aliases: [ spawneranalyze ]
    permission: rpg.admin
  스탯:
    description: 자신의 스탯 정보를 확인합니다.
    aliases: [내정보, stat, stats]
  # 관리자용 명령어는 편의를 위해 영어 유지
  rpworld:
    description: RPG 월드를 관리합니다.
    aliases: [rpgworld, wa]
    permission: rpg.admin
  rpgtest:
    description: RPG 시스템을 테스트합니다.
    aliases: [rt]
    permission: rpg.admin
  spawnset:
    description: unknown
    permission: rpg.admin.spawnset
  fieldadmin:
    description: 사냥터(필드)를 디버그하고 관리합니다.
    aliases: [fa]
    permission: rpg.admin.field
  rpgitem:
    description: 관리자가 모든 RPG 커스텀 아이템을 얻습니다.
    aliases: [ritem]
    permission: op # 권한을 OP로 설정